name: Run Cypress Tests
on: [push]
concurrency: cypress
jobs:
  buildAndRunCypressTests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: yarn

    - name: yarn install
      run: yarn install --frozen-lockfile

    - name: Cypress run
      uses: cypress-io/github-action@v2
      env:
        TESTING_DB_URL: ${{ secrets.TESTING_DB_URL }}
        PG_URL: ${{ secrets.PG_URL }}
        CHOKIDAR_USEPOLLING: 1
      with:
          start: |
            yarn ea-start-testing-db
            yarn ci-cypress-seed
          command: yarn ci-cypress-run

    - uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: Upload screenshots
        path: cypress/screenshots

    - uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: Upload videos
        path: cypress/videos
