name: Run Integration Tests
on: [push, pull_request]
concurrency: integration
jobs:
  buildAndTest:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: yarn install
      run: yarn install

    - name: Seed integration database
      env:
        TESTING_DB_URL: ${{ secrets.TESTING_DB_URL }}
        PG_URL: ${{ secrets.PG_URL }}
      run: yarn seed-integration-db

    - name: yarn run integration-ci
      env:
        PG_URL: ${{ secrets.PG_URL }}
        NODE_OPTIONS: "--max_old_space_size=4096"
      run: yarn run integration-ci
